const projectActionTypes = {
    SET_CURRENT_PROJECT:'SET_CURRENT_PROJECT',
    SET_REDIRECT_URIS:'SET_REDIRECT_URIS',
    SET_ORIGIN_URIS:'SET_ORIGIN_URIS',
    SET_APP_NAME:'SET_APP_NAME',
    SET_SECRET:'SET_SECRET',
    SET_DESCRIPTION:'SET_DESCRIPTION',
    SET_HOMEPAGE:'SET_HOMEPAGE',
    RESET_PROJECT:'RESET_PROJECT'
}

export default projectActionTypes